### ISSUE TITLE
Training seed setting

### ISSUE THREAD

**Issue by dy1998** [weiguoPian/AV-CIL_ICCV2023#4]
Hello, thanks for your wonderful work. May I ask if all experiments only use one seed（42 in code）?

Waiting for your kind reply.

**Comment by weiguoPian** [comment]
Hello,
Thank you for your interest in our work.
We run all the baseline methods and our method with the same random seed for fair comparison and reproducibility.

Bests,

**Comment by dy1998** [comment]
Thanks for your quick response!
