### ISSUE TITLE
VideoMAE extracted features, why is the frame number is 8?

### ISSUE THREAD

**Issue by ppx-hub** [weiguoPian/AV-CIL_ICCV2023#6]
Hello, thank you for your valuable article and for providing the features that have been extracted with VideoMAE.

If the pre-trained VideoMAE weights provided in the hugging face are used for feature extraction, the number of video frames required by the model should be 16, which corresponds to [gen_visual_features.py](https://github.com/weiguoPian/AV-CIL_ICCV2023/blob/main/utils/gen_visual_features.py).

Nonetheless, when I look at the model implementation, the code [audio_visual_model_incremental.py](https://github.com/weiguoPian/AV-CIL_ICCV2023/blob/main/model/audio_visual_model_incremental.py) reshapes the visual features to `visual = visual.view(visual.shape[0], 8, -1, 768)`, i.e., the temporal dimension is 8. Why is it not 16 here?

Am I missing something?

**Comment by weiguoPian** [comment]
Hello,

Thank you for your interests in our work.

The patches (named as cube in the VideoMAE paper) in the VideoMAE are with the shape of (2, 16, 16), which are split through both spatial and temporal dimensions. So that the temporal dimension will decrease from 16 to 8.

For more details, please refer to the VideoMAE paper.

Bests,

**Comment by ppx-hub** [comment]
> Hello,
> 
> Thank you for your interests in our work.
> 
> The patches (named as cube in the VideoMAE paper) in the VideoMAE are with the shape of (2, 16, 16), which are split through both spatial and temporal dimensions. So that the temporal dimension will decrease from 16 to 8.
> 
> For more details, please refer to the VideoMAE paper.
> 
> Bests,

Thanks for the reply, I understand.

Using audio-visual multimodal information to mitigate catastrophic forgetting in class incremental learning is very important to me. 

Thanks again for your outstanding work and open source code.
